== 회원

=== 회원 가입

operation::member-controller-test/register_member[snippets='http-request,http-response']

=== [ERROR] 회원 가입 시 이메일 중복

operation::member-controller-test/duplicate_register_member[snippets='http-request,http-response']

=== [ERROR] 이미 로그인에 성공한 사용자가 회원가입 시도

operation::member-controller-test/already_login_member_register[snippets='http-request,http-response']

=== 회원 토큰 검증

operation::member-controller-test/verify_member_token[snippets='http-request,http-response']

=== [ERROR] 유효하지 않은 회원 토큰으로 검증 시도

operation::member-controller-test/verify_member_invalid_token[snippets='http-request,http-response']

=== 로그인

operation::member-controller-test/login[snippets='http-request,http-response']

=== [ERROR] 존재하지 않는 이메일로 로그인 시도

operation::member-controller-test/login_notfound_member[snippets='http-request,http-response']

=== [ERROR] 이미 로그인에 성공한 사용자가 로그인 시도

operation::member-controller-test/already_login_member_login[snippets='http-request,http-response']

=== 구글 로그인

==== request

해당 URL로 접속하여 로그인 합니다. +
http://SERVER_URL/oauth2/authorization/google
변경

==== response

로그인에 성공하면 해당 URL로 리다이렉트 됩니다. +
http://SERVER_URL/oauth/success?token=ACCESS_TOKEN
